//! Bearer transactions: a redeemable "claim code" that ANYONE holding it can
//! sweep, with no recipient address chosen in advance. The code is really a
//! one-time private key in disguise, which is what makes it safe: a real key
//! has astronomically more entropy than a short PIN (no brute force), and
//! sweeping reveals only a signature bound to the claimer's own destination, so
//! the claim itself can't be front-run and re-pointed by a watcher.
//!
//! v1 is REVOCABLE: the throwaway key is generated by the sender's own node
//! (getnewaddress), so the sender retains it and can reclaim an unredeemed code
//! by sweeping it back. A future "true bearer" mode would generate the key
//! outside any wallet so the sender cannot reclaim (or betray) it.
//!
//! Everything here rides standard RPCs (getnewaddress, dumpprivkey,
//! sendtoaddress, gettxout, createrawtransaction, signrawtransaction,
//! sendrawtransaction). No consensus change, no key handling of our own.

use crate::config::NodeConfig;
use crate::rpc::RpcClient;
use base64::Engine;
use serde_json::json;

// A flat fee taken from the swept output. Comfortably above the 0.0001/kB relay
// minimum for a 1-in/1-out payment, and small enough not to matter.
const SWEEP_FEE: f64 = 0.0001;

pub struct BearerCreated {
    pub code: String,
    pub address: String,
    pub txid: String,
    pub vout: u32,
    pub amount: f64,
}

pub struct BearerStatus {
    pub funded: bool,
    pub claimed: bool,
    pub value: f64,
    /// What the redeemer actually receives (value minus the sweep fee). This is
    /// the number to show, since the sender already covered the fee.
    pub receivable: f64,
    pub confirmations: i64,
}

// code = "DVB1-" + base64url( "bearer.v1|<wif>|<txid>|<vout>|<amount>" )
fn encode_code(wif: &str, txid: &str, vout: u32, amount: f64) -> String {
    let payload = format!("bearer.v1|{wif}|{txid}|{vout}|{amount}");
    let b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(payload.as_bytes());
    format!("DVB1-{b64}")
}

struct Decoded {
    wif: String,
    txid: String,
    vout: u32,
}

fn decode_code(code: &str) -> Result<Decoded, String> {
    let body = code.trim().strip_prefix("DVB1-").ok_or("That is not a Divi bearer code.")?;
    let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(body.as_bytes())
        .map_err(|_| "That bearer code is malformed.".to_string())?;
    let text = String::from_utf8(bytes).map_err(|_| "That bearer code is malformed.".to_string())?;
    let parts: Vec<&str> = text.split('|').collect();
    if parts.len() != 5 || parts[0] != "bearer.v1" {
        return Err("That bearer code is not a supported version.".into());
    }
    Ok(Decoded {
        wif: parts[1].to_string(),
        txid: parts[2].to_string(),
        vout: parts[3].parse().map_err(|_| "That bearer code is malformed.".to_string())?,
    })
}

/// Create a bearer code funded with `amount` DIVI. The funding output pays a
/// fresh node-owned address; the code carries that address's key plus the exact
/// output to sweep, so a claimer needs no address index to find it.
pub fn create(cfg: &NodeConfig, amount: f64, passphrase: Option<&str>) -> Result<BearerCreated, String> {
    if amount <= 0.0 {
        return Err("Amount must be greater than zero.".into());
    }
    // Sender pays the fee. We fund the code with amount + the sweep fee, so that
    // after the claimer's sweep takes SWEEP_FEE the RECEIVER gets the full
    // `amount`. `amount` (what the receiver gets) is what we display and encode.
    let funded = round8(amount + SWEEP_FEE);
    let rpc = RpcClient::new(cfg);

    if let Some(pass) = passphrase {
        rpc.call("walletpassphrase", json!([pass, 120, false]))
            .map_err(|e| format!("Unlock failed: {e}"))?;
    }
    // Do the spend work, capturing any error so we always re-lock afterwards.
    let result = (|| {
        let address = rpc
            .call("getnewaddress", json!(["bearer"]))?
            .as_str()
            .ok_or("node did not return an address")?
            .to_string();
        let wif = rpc
            .call("dumpprivkey", json!([address]))?
            .as_str()
            .ok_or("node did not return a key")?
            .to_string();
        let txid = rpc
            .call("sendtoaddress", json!([address, funded]))?
            .as_str()
            .ok_or("node did not return a transaction id")?
            .to_string();
        // Which output paid the bearer address? sendtoaddress makes payment +
        // change, so check the small candidate set against the UTXO set.
        let vout = find_vout(&rpc, &txid, &address).ok_or("could not locate the funding output")?;
        Ok(BearerCreated {
            code: encode_code(&wif, &txid, vout, amount),
            address,
            txid,
            vout,
            amount,
        })
    })();

    if let Some(pass) = passphrase {
        let _ = rpc.call("walletpassphrase", json!([pass, 0, true]));
    }
    result
}

/// Sweep a bearer output to `dest`. Used both for a recipient claiming and for
/// the sender reclaiming (same operation, different destination). Signs with
/// the code's own key, so the claimer's wallet need not be unlocked.
pub fn sweep(cfg: &NodeConfig, code: &str, dest: &str) -> Result<String, String> {
    let d = decode_code(code)?;
    let rpc = RpcClient::new(cfg);

    // includemempool = true, so a just-broadcast fund is claimable immediately.
    let utxo = rpc.call("gettxout", json!([d.txid, d.vout, true]))?;
    if utxo.is_null() {
        return Err("This code has already been claimed (or was never funded).".into());
    }
    let value = utxo["value"].as_f64().ok_or("could not read the output value")?;
    let spk = utxo["scriptPubKey"]["hex"].as_str().ok_or("could not read the output script")?.to_string();
    if value <= SWEEP_FEE {
        return Err("The bearer output is too small to sweep.".into());
    }
    let send_value = round8(value - SWEEP_FEE);

    let raw = rpc
        .call("createrawtransaction", json!([[{"txid": d.txid, "vout": d.vout}], {dest: send_value}]))?
        .as_str()
        .ok_or("could not build the claim transaction")?
        .to_string();

    let prevtxs = json!([{"txid": d.txid, "vout": d.vout, "scriptPubKey": spk}]);
    let signed = rpc.call("signrawtransaction", json!([raw, prevtxs, [d.wif]]))?;
    if signed["complete"].as_bool() != Some(true) {
        return Err("Could not sign the claim (the code may be invalid).".into());
    }
    let signed_hex = signed["hex"].as_str().ok_or("signing produced no transaction")?;

    let sent = rpc
        .call("sendrawtransaction", json!([signed_hex]))?
        .as_str()
        .ok_or("the node did not confirm the broadcast")?
        .to_string();
    Ok(sent)
}

/// Is this code still claimable? Reads the UTXO set only (no secrets needed
/// beyond the code, no wallet unlock).
pub fn status(cfg: &NodeConfig, code: &str) -> Result<BearerStatus, String> {
    let d = decode_code(code)?;
    let rpc = RpcClient::new(cfg);
    let utxo = rpc.call("gettxout", json!([d.txid, d.vout, true]))?;
    if utxo.is_null() {
        // Spent (claimed/reclaimed) or the funding never confirmed/propagated.
        return Ok(BearerStatus { funded: false, claimed: true, value: 0.0, receivable: 0.0, confirmations: 0 });
    }
    let value = utxo["value"].as_f64().unwrap_or(0.0);
    Ok(BearerStatus {
        funded: true,
        claimed: false,
        value,
        receivable: round8((value - SWEEP_FEE).max(0.0)),
        confirmations: utxo["confirmations"].as_i64().unwrap_or(0),
    })
}

// Match the funding output to the bearer address by scanning the small set of
// vouts sendtoaddress can produce (payment + change). Uses the UTXO set, so it
// needs no -txindex.
fn find_vout(rpc: &RpcClient, txid: &str, address: &str) -> Option<u32> {
    for n in 0..4u32 {
        if let Ok(o) = rpc.call("gettxout", json!([txid, n, true])) {
            if o.is_null() {
                continue;
            }
            let matches = o["scriptPubKey"]["addresses"]
                .as_array()
                .map(|a| a.iter().any(|x| x.as_str() == Some(address)))
                .unwrap_or(false);
            if matches {
                return Some(n);
            }
        }
    }
    None
}

fn round8(v: f64) -> f64 {
    (v * 1e8).round() / 1e8
}
